services:
  - type: worker
    name: trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python /opt/render/project/src/trading_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
